[tool.poetry]
name = "maze-transformer"
version = "0.0.1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "maze_transformer"}]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
# Ignore numpy deprecation warnings triggered by muutils
filterwarnings = "ignore:`np\\.\\w*` is a deprecated alias for:DeprecationWarning"

[[tool.mypy.overrides]]
module = "fire"
ignore_missing_imports = true

[tool.isort]
profile = "black"
