[tool.poetry]
name = "maze-transformer"
version = "0.0.1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "maze_transformer"}]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^1.13.1"
transformer-lens = "^1.1.1"
matplotlib = "^3.7.0"
fire = "^0.5.0"
muutils = "0.2.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pycln = "^2.1.3"
isort = "^5.12.0"
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
# Ignore numpy deprecation warnings triggered by muutils
filterwarnings = [
    # Warning from muutils: https://github.com/mivanit/muutils/issues/1
    "ignore:`np\\.\\w*` is a deprecated alias for:DeprecationWarning",

    # Warning from matplotlib. Issue: https://github.com/matplotlib/matplotlib/issues/25244
    "ignore:Deprecated call to `pkg_resources.declare_namespace:DeprecationWarning"
]

[[tool.mypy.overrides]]
module = "fire"
ignore_missing_imports = true

[tool.isort]
profile = "black"
