[build]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "maze_transformer"
version = "0.0.1"
dependencies = [
  "numpy == 1.23.1",
  "matplotlib",
  "muutils",
  "fire",
]

[tool.pytest.ini_options]
# Ignore numpy deprecation warnings triggered by muutils
filterwarnings = "ignore:`np\\.\\w*` is a deprecated alias for:DeprecationWarning"
